apiVersion: v1
kind: Service
metadata:
  name: {{ include "movie-service.fullname" . }}
spec:
  selector:
    app: movie-service
  ports:
    - protocol: TCP
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.servicePort }}
