containers:
  - name: movie-service
    image: {{ .Values.movieService.image.repository }}:{{ .Values.movieService.image.tag }}
    imagePullPolicy: {{ .Values.movieService.image.pullPolicy }}
    ports:
      - containerPort: 8000

containers:
  - name: cast-service
    image: {{ .Values.castService.image.repository }}:{{ .Values.castService.image.tag }}
    imagePullPolicy: {{ .Values.castService.image.pullPolicy }}
    ports:
      - containerPort: 8000