movie:
  database:
    name: movie_db_dev
    username: movie_db_username
    password: movie_db_password

cast:
  database:
    name: cast_db_dev
    username: cast_db_username
    password: cast_db_password
