apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cast-db
spec:
  serviceName: cast-db
  replicas: 1
  selector:
    matchLabels:
      app: cast-db
  template:
    metadata:
      labels:
        app: cast-db
    spec:
      containers:
        - name: postgres
          image: postgres:12.1-alpine
          env:
            - name: POSTGRES_USER
              value: {{ .Values.cast.database.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.cast.database.password }}
            - name: POSTGRES_DB
              value: {{ .Values.cast.database.name }}
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgresql-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
