replicaCount: 1

image:
  repository: "jlnlndr17/cast-service"
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  port: 8000
  targetPort: 8000
  type: ClusterIP

env:
  - name: DATABASE_URI
    value: "postgresql://cast_db_username:cast_db_password@cast_db/cast_db_dev"

serviceAccount:
  create: true  # Ajout de cette ligne pour définir serviceAccount.create à true

ingress:
  enabled: false

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
