apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "movie-service.fullname" . }}
  labels:
    app: {{ include "movie-service.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "movie-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "movie-service.name" . }}
    spec:
      containers:
        - name: {{ include "movie-service.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.servicePort }}
          env:
            - name: DATABASE_URI
              value: "postgresql://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.name }}/movie_db_dev"
          # Add other environment variables if needed
          # - name: ENV_VAR_NAME
          #   value: "VALUE"
