# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: {{ include "movie-service.fullname" . }}
spec:
  selector:
    app: {{ include "movie-service.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}
